version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9.10-management
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: tuum
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sql
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  queue-receiver:
    build:
      context: ./queueReceiver
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
    - database
    - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/tuum
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: sql
      RABBITMQ_SERVER: rabbitmq
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest


  queue-producer:
    build:
      context: ./queueProducer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
    - database
    - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/tuum
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: sql
      RABBITMQ_SERVER: rabbitmq
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest